
package proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControladorPedidoPublicador", targetNamespace = "http://servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControladorPedidoPublicador {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns client.DataPedido
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/ControladorPedidoPublicador/realizarPedidoRequest", output = "http://servidor/ControladorPedidoPublicador/realizarPedidoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/realizarPedido/Fault/Exception")
    })
    public DataPedido realizarPedido(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        StringArray arg2,
        @WebParam(name = "arg3", partName = "arg3")
        IntArray arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns client.DataPedidoArray
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/ControladorPedidoPublicador/listarPedidos2Request", output = "http://servidor/ControladorPedidoPublicador/listarPedidos2Response", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/listarPedidos2/Fault/Exception")
    })
    public DataPedidoArray listarPedidos2(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://servidor/ControladorPedidoPublicador/cancelarPedidoRequest", output = "http://servidor/ControladorPedidoPublicador/cancelarPedidoResponse")
    public void cancelarPedido();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://servidor/ControladorPedidoPublicador/limpiarMermoriaRequest", output = "http://servidor/ControladorPedidoPublicador/limpiarMermoriaResponse")
    public void limpiarMermoria();

    /**
     * 
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/ControladorPedidoPublicador/actualizarPedidoRequest", output = "http://servidor/ControladorPedidoPublicador/actualizarPedidoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/actualizarPedido/Fault/Exception")
    })
    public void actualizarPedido()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/ControladorPedidoPublicador/agregarComentarioRequest", output = "http://servidor/ControladorPedidoPublicador/agregarComentarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/agregarComentario/Fault/Exception")
    })
    public void agregarComentario(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        float arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns client.DataPedidoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/ControladorPedidoPublicador/listarPedidosRequest", output = "http://servidor/ControladorPedidoPublicador/listarPedidosResponse")
    public DataPedidoArray listarPedidos();

}
