/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datatype.DataProducto;
import datatype.DataRestaurante;
import fabrica.Fabrica;
import interfaces.IControladorCategoria;
import interfaces.IControladorProducto;
import interfaces.IControladorUsuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathi
 */
public class RegistrarProducto extends javax.swing.JInternalFrame {
    private 
        DataRestaurante[] restaurantes;
        Float cPrecio;
        String imagenSrc, Extension,NombreArchivo;
        String outFile, inFile;
        
         
    IControladorCategoria iCat = Fabrica.getInstance().obtenerControladorCategoria();
    IControladorUsuario iUsr = Fabrica.getInstance().obtenerControladorUsuario();
    
    private IControladorProducto iProd;
    
    private DefaultListModel modeloOut=new DefaultListModel();
    private DefaultTableModel modeloIn=(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
        "Producto", "Cantidad"
    }
));
    /**
     * Creates new form RegistrarProducto
     */
    public RegistrarProducto() {
        imagenSrc="";
        outFile="";
        NombreArchivo="";
        List<DataRestaurante> temp=iUsr.listarRestaurantes();
        restaurantes=temp.toArray(new DataRestaurante[temp.size()]);
        initComponents();
        
        this.jTextFieldNombre.setText("");
        this.jTextAreaDescripcion.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldDescuento.setText("");
        this.jTextFieldPrecio.setText("");
        
        tipoProducto.add(jRadioButtonPromocion);
        tipoProducto.add(jRadioButtonIndividual);
        jRadioButtonIndividual.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoProducto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxRestaurante = new javax.swing.JComboBox();
        jRadioButtonIndividual = new javax.swing.JRadioButton();
        jRadioButtonPromocion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PanelGenerico = new javax.swing.JPanel();
        panelIndividual = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        panelPromocion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList();
        jButtonAgregar = new javax.swing.JButton();
        jButtonQuitar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProductos2 = new javax.swing.JTable(){     public boolean isCellEditable(int row, int column) {         return (column == 23 );     } };
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDescuento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonImage = new javax.swing.JButton();

        setTitle("Registrar Producto");

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripción");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jLabel3.setText("Restaurante");

        jComboBoxRestaurante.setModel(new javax.swing.DefaultComboBoxModel(restaurantes));
        jComboBoxRestaurante.setSelectedItem(new javax.swing.DefaultComboBoxModel(restaurantes));

        tipoProducto.add(jRadioButtonIndividual);
        jRadioButtonIndividual.setSelected(true);
        jRadioButtonIndividual.setText("Individual");
        jRadioButtonIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIndividualActionPerformed(evt);
            }
        });

        tipoProducto.add(jRadioButtonPromocion);
        jRadioButtonPromocion.setText("Promoción");
        jRadioButtonPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPromocionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tipo:");

        PanelGenerico.setLayout(new java.awt.CardLayout());

        jLabel5.setText("Precio");

        javax.swing.GroupLayout panelIndividualLayout = new javax.swing.GroupLayout(panelIndividual);
        panelIndividual.setLayout(panelIndividualLayout);
        panelIndividualLayout.setHorizontalGroup(
            panelIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndividualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIndividualLayout.setVerticalGroup(
            panelIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIndividualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        PanelGenerico.add(panelIndividual, "card2");

        listaProductos.setModel(modeloOut);
        jScrollPane2.setViewportView(listaProductos);

        jButtonAgregar.setText(">>");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonQuitar.setText("<<");
        jButtonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitarActionPerformed(evt);
            }
        });

        listaProductos2.setModel(modeloIn);
        jScrollPane3.setViewportView(listaProductos2);

        jLabel6.setText("Descuento");

        jLabel7.setText("%");

        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setText("1");
        cantidad.setToolTipText("");

        jLabel8.setText("Cantidad");

        javax.swing.GroupLayout panelPromocionLayout = new javax.swing.GroupLayout(panelPromocion);
        panelPromocion.setLayout(panelPromocionLayout);
        panelPromocionLayout.setHorizontalGroup(
            panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPromocionLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonQuitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
            .addGroup(panelPromocionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPromocionLayout.setVerticalGroup(
            panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPromocionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPromocionLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitar)
                        .addGap(23, 23, 23)))
                .addGap(18, 18, 18)
                .addGroup(panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        PanelGenerico.add(panelPromocion, "card3");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonImage.setText("Seleccionar Imagen");
        jButtonImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonImage)
                            .addComponent(jComboBoxRestaurante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextFieldNombre)))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelGenerico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCancelar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jButtonRegistrar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonPromocion)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonIndividual)
                                .addGap(53, 53, 53)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonPromocion)
                    .addComponent(jRadioButtonIndividual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPromocionActionPerformed
        PanelGenerico.removeAll();        
        PanelGenerico.add(panelPromocion);
        PanelGenerico.repaint();
        PanelGenerico.revalidate();  
        
        DataRestaurante selectedRes=(DataRestaurante)this.jComboBoxRestaurante.getSelectedItem();
        ArrayList<DataProducto> productos = iUsr.listarProductos(selectedRes.getNickname());
        modeloOut.clear();
        for (DataProducto p : productos){
            modeloOut.addElement(p.getNombre());
        }
    }//GEN-LAST:event_jRadioButtonPromocionActionPerformed

    private void jRadioButtonIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIndividualActionPerformed
        PanelGenerico.removeAll();        
        PanelGenerico.add(panelIndividual);
        PanelGenerico.repaint();
        PanelGenerico.revalidate();
    }//GEN-LAST:event_jRadioButtonIndividualActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImageActionPerformed
        FileFilter filter = new FileNameExtensionFilter("Imagenes (.jpg .png)","jpg", "png");

        JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setAcceptAllFileFilterUsed(false);
        elegirImagen.addChoosableFileFilter(filter);
        int opt = elegirImagen.showOpenDialog(jButtonImage);

        
        if (opt == JFileChooser.APPROVE_OPTION) {
            imagenSrc = elegirImagen.getSelectedFile().getPath();
            NombreArchivo = elegirImagen.getSelectedFile().getName();    
        }
    }//GEN-LAST:event_jButtonImageActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        IControladorProducto iProd = Fabrica.getInstance().obtenerControladorProducto();
        boolean camposVacios=false;
        String cNombre,cDescripcion,cPrecio,cDescuento,cCantidad;
        cNombre=this.jTextFieldNombre.getText();
        cDescripcion=this.jTextAreaDescripcion.getText();
        cPrecio= this.jTextFieldPrecio.getText();
        cDescuento=this.jTextFieldDescuento.getText();
       
        
        if("".equals(cNombre) || "".equals(cDescripcion)){
            camposVacios=true;
        }
        
        DataRestaurante selectedRes=(DataRestaurante)this.jComboBoxRestaurante.getSelectedItem();
        
        if (!"".equals(imagenSrc)){
            /* INGRESAR IMAGEN
            iProd.ingresarImagen(imagenSrc);*/
        }
        
        iProd.seleccionarRestaurante(selectedRes.getNickname());
        
        //individual
        if (jRadioButtonIndividual.isSelected()){
            
            //Carga Archivo de Propiedades ----------------------
                Properties propiedades = new Properties();
                InputStream entrada = null;
                try {               
                    entrada = this.getClass().getResourceAsStream("/Resources/config.properties");
                    propiedades.load(entrada);
                    } 
                catch (IOException ex) {
                    ex.printStackTrace();
                } 
                //---------------------------------------------------
                
                try{
                    String inFile = imagenSrc;
                    
                    Extension = NombreArchivo.substring(NombreArchivo.lastIndexOf("."),NombreArchivo.length());
                    outFile = propiedades.getProperty("imagenesProductos")+cNombre+"-"+selectedRes.getNickname()+Extension;
               
                    System.out.println(inFile);
                    System.out.println(outFile);
                    
                    FileInputStream fis = new FileInputStream(inFile); //inFile -> Archivo a copiar
                    FileOutputStream fos = new FileOutputStream(outFile); //outFile -> Copia del archivo
                    
                    FileChannel inChannel = fis.getChannel();
                    FileChannel outChannel = fos.getChannel();
                    
                    inChannel.transferTo(0, inChannel.size(), outChannel);
                    fis.close();
                    fos.close();

                   }catch (IOException ioe) {
                    System.err.println("Error al Generar Copia");
                   }
            
            iProd.cargarDatosProducto(cNombre, cDescripcion, Float.parseFloat(cPrecio), outFile);
            
            if ("".equals(cPrecio)){
                camposVacios=true;
            }
            
        }
        //promocion
        
        else{
            
            if ("".equals(cDescuento) || listaProductos2.getRowCount()==0){
                camposVacios=true;
            }
            else{
                iProd.cargarDatosProducto(cNombre, cDescripcion, Integer.parseInt(cDescuento), outFile);
                for (int i=0;i<listaProductos2.getRowCount();i++){
                    String prod=(String)listaProductos2.getValueAt(i, 0);
                    String cant=(String)listaProductos2.getValueAt(i, 1);
                    
                    iProd.seleccionarProducto(prod, Integer.parseInt(cant));
                }
            }
        }
        
        if (!camposVacios){
            try{
                iProd.altaProducto();
                JOptionPane.showMessageDialog(this,"Producto registrado");
                this.setVisible(false);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "", JOptionPane.ERROR_MESSAGE);
            }            
        }
        else{
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        int index = listaProductos.getSelectedIndex();
        if(index != -1){
            String[] fila = new String[2];
            fila[0] = (String) modeloOut.getElementAt(index);
            fila[1] = this.cantidad.getText();;
            modeloIn.addRow(fila);
            modeloOut.remove(index);
            this.cantidad.setText("1");

        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitarActionPerformed
        int index = listaProductos2.getSelectedRow();
        if (index != -1){
            modeloOut.addElement(modeloIn.getValueAt(index, 0));
            modeloIn.removeRow(index);

        }
    }//GEN-LAST:event_jButtonQuitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGenerico;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImage;
    private javax.swing.JButton jButtonQuitar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox jComboBoxRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButtonIndividual;
    private javax.swing.JRadioButton jRadioButtonPromocion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldDescuento;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JList listaProductos;
    private javax.swing.JTable listaProductos2;
    private javax.swing.JPanel panelIndividual;
    private javax.swing.JPanel panelPromocion;
    private javax.swing.ButtonGroup tipoProducto;
    // End of variables declaration//GEN-END:variables
}
