/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datatype.DataCliente;
import fabrica.Fabrica;
import interfaces.IControladorUsuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.util.ArrayList;

/**
 *
 * @author Mathi
 */
public class VerInformacionDeCliente extends javax.swing.JInternalFrame {

    private Object[][] dataClientes;
    private IControladorUsuario iUsr = Fabrica.getInstance().obtenerControladorUsuario();
    //private IUsuario iUsr=Sistema.getInstance().getIUsuario();

    /**
     * Creates new form VerInformacionDeCliente
     */
    public VerInformacionDeCliente() {

        ArrayList<DataCliente> clientes = iUsr.listarClientes();

        if (!clientes.isEmpty()) {
            ArrayList<Object[]> temp = new ArrayList();
            Object[] current;
            for (DataCliente c : clientes) {
                current = new Object[]{c.getNickname(), c.getMail(), c};
                temp.add(current);
            }

            dataClientes = temp.toArray(new Object[temp.size()][3]);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        tablaDeClientes = new javax.swing.JTable();
        imagenCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nicknameCliente = new javax.swing.JLabel();
        mailCliente = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JLabel();
        apellidoCliente = new javax.swing.JLabel();
        direccionCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonVerPedido = new javax.swing.JButton();
        jButtonCancelar3 = new javax.swing.JButton();

        setTitle("Ver información del Cliente");

        tablaDeClientes.setModel(new javax.swing.table.DefaultTableModel( dataClientes,  new String [] { "Nickname", "Mail" }){
            public boolean isCellEditable(int row, int column) {
                return (column == 23 );
            }
        });
        tablaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDeClientesMouseClicked(evt);
            }
        });
        scroll.setViewportView(tablaDeClientes);

        imagenCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nickname");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mail");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dirección");

        nicknameCliente.setText("Nickname");

        mailCliente.setText("Mail");

        nombreCliente.setText("Nombre");

        apellidoCliente.setText("Apellido");

        direccionCliente.setText("Dirección");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Clientes del Sistema:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Pedidos del Cliente:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButtonVerPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVerPedido.setText("Ver Pedido");
        jButtonVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPedidoActionPerformed(evt);
            }
        });

        jButtonCancelar3.setText("Cancelar");
        jButtonCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(scroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionCliente)
                            .addComponent(apellidoCliente)
                            .addComponent(nombreCliente)
                            .addComponent(mailCliente)
                            .addComponent(nicknameCliente))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVerPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCancelar3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nicknameCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mailCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apellidoCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(direccionCliente))))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerPedidoActionPerformed

    private void jButtonCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar3ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelar3ActionPerformed

    private void tablaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDeClientesMouseClicked
        int i = tablaDeClientes.getSelectedRow();
        if (i != -1) {
            DataCliente c = (DataCliente) dataClientes[i][2];

            nicknameCliente.setText(c.getNickname());
            apellidoCliente.setText(c.getApellido());
            //direccionCliente.setText(c.getDireccion());
            mailCliente.setText(c.getMail());
            nombreCliente.setText(c.getNombre());

            String img = c.getRutaImagen();

            if (img == null) {
                    //Image image = Toolkit.getDefaultToolkit().createImage(IMAGEN POR DEFECTO);
                //Icon warnIcon = new ImageIcon(image);
                // imagenCliente.setIcon(warnIcon);
                //imagenCliente.validate();
            } else {

                Image image = Toolkit.getDefaultToolkit().createImage(img);
                Icon warnIcon = new ImageIcon(image);
                imagenCliente.setIcon(warnIcon);
                imagenCliente.validate();

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDeClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoCliente;
    private javax.swing.JLabel direccionCliente;
    private javax.swing.JLabel imagenCliente;
    private javax.swing.JButton jButtonCancelar3;
    private javax.swing.JButton jButtonVerPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel mailCliente;
    private javax.swing.JLabel nicknameCliente;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaDeClientes;
    // End of variables declaration//GEN-END:variables

    private IControladorUsuario obtenerControladorUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
