
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControladorUsuarioPublicadorService", targetNamespace = "http://servidor/", wsdlLocation = "http://localhost:9129/usuario?wsdl")
public class ControladorUsuarioPublicadorService
    extends Service
{

    private final static URL CONTROLADORUSUARIOPUBLICADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORUSUARIOPUBLICADORSERVICE_EXCEPTION;
    private final static QName CONTROLADORUSUARIOPUBLICADORSERVICE_QNAME = new QName("http://servidor/", "ControladorUsuarioPublicadorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9129/usuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORUSUARIOPUBLICADORSERVICE_WSDL_LOCATION = url;
        CONTROLADORUSUARIOPUBLICADORSERVICE_EXCEPTION = e;
    }

    public ControladorUsuarioPublicadorService() {
        super(__getWsdlLocation(), CONTROLADORUSUARIOPUBLICADORSERVICE_QNAME);
    }

    public ControladorUsuarioPublicadorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORUSUARIOPUBLICADORSERVICE_QNAME, features);
    }

    public ControladorUsuarioPublicadorService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORUSUARIOPUBLICADORSERVICE_QNAME);
    }

    public ControladorUsuarioPublicadorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORUSUARIOPUBLICADORSERVICE_QNAME, features);
    }

    public ControladorUsuarioPublicadorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorUsuarioPublicadorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControladorUsuarioPublicador
     */
    @WebEndpoint(name = "ControladorUsuarioPublicadorPort")
    public ControladorUsuarioPublicador getControladorUsuarioPublicadorPort() {
        return super.getPort(new QName("http://servidor/", "ControladorUsuarioPublicadorPort"), ControladorUsuarioPublicador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorUsuarioPublicador
     */
    @WebEndpoint(name = "ControladorUsuarioPublicadorPort")
    public ControladorUsuarioPublicador getControladorUsuarioPublicadorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor/", "ControladorUsuarioPublicadorPort"), ControladorUsuarioPublicador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORUSUARIOPUBLICADORSERVICE_EXCEPTION!= null) {
            throw CONTROLADORUSUARIOPUBLICADORSERVICE_EXCEPTION;
        }
        return CONTROLADORUSUARIOPUBLICADORSERVICE_WSDL_LOCATION;
    }

}
