
package proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControladorPedidoPublicador", targetNamespace = "http://servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControladorPedidoPublicador {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.DataPedidoArray
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/ControladorPedidoPublicador/listarPedidos2Request", output = "http://servidor/ControladorPedidoPublicador/listarPedidos2Response", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/listarPedidos2/Fault/Exception")
    })
    public DataPedidoArray listarPedidos2(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param cantidades
     * @param nickNameCliente
     * @param nickNameRestaurante
     * @param productos
     * @return
     *     returns proxy.DataPedido
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/ControladorPedidoPublicador/realizarPedidoRequest", output = "http://servidor/ControladorPedidoPublicador/realizarPedidoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/realizarPedido/Fault/Exception")
    })
    public DataPedido realizarPedido(
        @WebParam(name = "nickNameCliente", partName = "nickNameCliente")
        String nickNameCliente,
        @WebParam(name = "nickNameRestaurante", partName = "nickNameRestaurante")
        String nickNameRestaurante,
        @WebParam(name = "productos", partName = "productos")
        StringArray productos,
        @WebParam(name = "cantidades", partName = "cantidades")
        IntArray cantidades)
        throws Exception_Exception
    ;

    /**
     * 
     * @param nuevoEstadoPedido
     * @param numeroPedido
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/ControladorPedidoPublicador/actualizarPedidoRequest", output = "http://servidor/ControladorPedidoPublicador/actualizarPedidoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/actualizarPedido/Fault/Exception")
    })
    public void actualizarPedido(
        @WebParam(name = "numeroPedido", partName = "numeroPedido")
        int numeroPedido,
        @WebParam(name = "nuevoEstadoPedido", partName = "nuevoEstadoPedido")
        EnumEstado nuevoEstadoPedido)
        throws Exception_Exception
    ;

    /**
     * 
     * @param puntuacion
     * @param numeroPedido
     * @param comentario
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://servidor/ControladorPedidoPublicador/agregarComentarioRequest", output = "http://servidor/ControladorPedidoPublicador/agregarComentarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://servidor/ControladorPedidoPublicador/agregarComentario/Fault/Exception")
    })
    public void agregarComentario(
        @WebParam(name = "numeroPedido", partName = "numeroPedido")
        int numeroPedido,
        @WebParam(name = "comentario", partName = "comentario")
        String comentario,
        @WebParam(name = "puntuacion", partName = "puntuacion")
        float puntuacion)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns proxy.DataPedidoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor/ControladorPedidoPublicador/listarPedidosRequest", output = "http://servidor/ControladorPedidoPublicador/listarPedidosResponse")
    public DataPedidoArray listarPedidos();

}
