/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathi
 */
public class QOMobileGUI extends javax.swing.JFrame {

    /**
     * Creates new form QOMobileGUI2
     */
    public QOMobileGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        general = new javax.swing.JPanel();
        sesionCerrada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        verPedido = new javax.swing.JPanel();
        labelInfoPedido = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        labelProductos = new javax.swing.JLabel();
        labelHistorial = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        labelEstadoActual = new javax.swing.JLabel();
        estadoActual = new javax.swing.JLabel();
        labelNuevoEstado = new javax.swing.JLabel();
        cambioEstados = new javax.swing.JComboBox();
        volver = new javax.swing.JButton();
        actualizarEstado = new javax.swing.JButton();
        scrollTablaProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        scrollTablaHistorial = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        sesionIniciada = new javax.swing.JPanel();
        cerrarSesion = new javax.swing.JButton();
        usuarioLogeado = new javax.swing.JLabel();
        estadoConexion = new javax.swing.JLabel();
        pedidos = new javax.swing.JLabel();
        scrollTablaPedidos = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        Actualizar = new javax.swing.JButton();
        ver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 480));
        setResizable(false);

        general.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("USUARIO:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD:");

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sesionCerradaLayout = new javax.swing.GroupLayout(sesionCerrada);
        sesionCerrada.setLayout(sesionCerradaLayout);
        sesionCerradaLayout.setHorizontalGroup(
            sesionCerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesionCerradaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(sesionCerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass)
                    .addComponent(user)
                    .addGroup(sesionCerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        sesionCerradaLayout.setVerticalGroup(
            sesionCerradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sesionCerradaLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        general.add(sesionCerrada, "card2");

        labelInfoPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelInfoPedido.setText("INFORMACION DEL PEDIDO");

        labelUsuario.setText("Usuario:");

        usuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuario.setText("usuario");

        labelFecha.setText("Fecha:");

        fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fecha.setText("fecha");

        labelProductos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelProductos.setText("Productos:");

        labelHistorial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelHistorial.setText("Historial:");

        labelPrecio.setText("Precio total:");

        precio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        precio.setText("precio");

        labelEstadoActual.setText("Estado actual:");

        estadoActual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        estadoActual.setText("estado");

        labelNuevoEstado.setText("Nuevo estado:");

        cambioEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cambioEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioEstadosActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        actualizarEstado.setText("Actualizar estado");
        actualizarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarEstadoActionPerformed(evt);
            }
        });

        medeloProductos = new DefaultTableModel();
        medeloProductos.addColumn("Producto");
        medeloProductos.addColumn("Cantidad");
        medeloProductos.addColumn("Precio");
        medeloProductos.addColumn("Subtotal");
        tablaProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaProductos.setModel(medeloProductos);
        scrollTablaProductos.setViewportView(tablaProductos);

        historial = new DefaultTableModel();
        historial.addColumn("Estado");
        historial.addColumn("Fecha");
        tablaHistorial = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return column == 4;
            }
        };
        tablaHistorial.setModel(historial);
        scrollTablaHistorial.setViewportView(tablaHistorial);

        javax.swing.GroupLayout verPedidoLayout = new javax.swing.GroupLayout(verPedido);
        verPedido.setLayout(verPedidoLayout);
        verPedidoLayout.setHorizontalGroup(
            verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verPedidoLayout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(verPedidoLayout.createSequentialGroup()
                        .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(verPedidoLayout.createSequentialGroup()
                                .addComponent(labelFecha)
                                .addGap(18, 18, 18)
                                .addComponent(fecha))
                            .addGroup(verPedidoLayout.createSequentialGroup()
                                .addComponent(labelNuevoEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cambioEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(verPedidoLayout.createSequentialGroup()
                                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEstadoActual)
                                    .addComponent(labelPrecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precio)
                                    .addComponent(estadoActual)))
                            .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, verPedidoLayout.createSequentialGroup()
                                    .addComponent(volver)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(actualizarEstado))
                                .addComponent(scrollTablaHistorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(verPedidoLayout.createSequentialGroup()
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelProductos))
                    .addGroup(verPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelHistorial))
                    .addGroup(verPedidoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(labelInfoPedido)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        verPedidoLayout.setVerticalGroup(
            verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInfoPedido)
                .addGap(4, 4, 4)
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadoActual)
                    .addComponent(estadoActual))
                .addGap(18, 18, 18)
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevoEstado)
                    .addComponent(cambioEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(verPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actualizarEstado))
                .addGap(101, 101, 101))
        );

        general.add(verPedido, "card2");

        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        usuarioLogeado.setText("usuario");

        estadoConexion.setText("estado conexion");

        pedidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pedidos.setText("Pedidos");

        modeloPedidos = new DefaultTableModel();
        modeloPedidos.addColumn("Numero");
        modeloPedidos.addColumn("Cliente");
        modeloPedidos.addColumn("Estado");
        modeloPedidos.addColumn("Fecha");
        tablaPedidos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaPedidos.setModel(modeloPedidos);
        scrollTablaPedidos.setViewportView(tablaPedidos);

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        ver.setText("Ver");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sesionIniciadaLayout = new javax.swing.GroupLayout(sesionIniciada);
        sesionIniciada.setLayout(sesionIniciadaLayout);
        sesionIniciadaLayout.setHorizontalGroup(
            sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesionIniciadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sesionIniciadaLayout.createSequentialGroup()
                        .addGroup(sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pedidos)
                            .addGroup(sesionIniciadaLayout.createSequentialGroup()
                                .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuarioLogeado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estadoConexion))))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addComponent(scrollTablaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(sesionIniciadaLayout.createSequentialGroup()
                        .addComponent(Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ver)))
                .addContainerGap())
        );
        sesionIniciadaLayout.setVerticalGroup(
            sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sesionIniciadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sesionIniciadaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(usuarioLogeado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoConexion))
                    .addGroup(sesionIniciadaLayout.createSequentialGroup()
                        .addComponent(cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sesionIniciadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar))
                .addGap(25, 25, 25))
        );

        general.add(sesionIniciada, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(general, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
                    general.removeAll();
                    general.add(sesionIniciada);
                    general.repaint();
                    general.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed

        // RECARGAR PEDIOS
        general.removeAll();
        general.add(sesionIniciada);
        general.repaint();
        general.revalidate();
    }//GEN-LAST:event_volverActionPerformed

    private void actualizarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarEstadoActionPerformed
       
    }//GEN-LAST:event_actualizarEstadoActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

        // CERRAR LA SESION
        general.removeAll();
        general.add(sesionCerrada);
        general.repaint();
        general.revalidate();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
       
    }//GEN-LAST:event_ActualizarActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        
        general.removeAll();
        general.add(verPedido);
        general.repaint();
        general.revalidate();
    }//GEN-LAST:event_verActionPerformed

    private void cambioEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambioEstadosActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QOMobileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QOMobileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QOMobileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QOMobileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QOMobileGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton actualizarEstado;
    private javax.swing.JComboBox cambioEstados;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel estadoActual;
    private javax.swing.JLabel estadoConexion;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel general;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelEstadoActual;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHistorial;
    private javax.swing.JLabel labelInfoPedido;
    private javax.swing.JLabel labelNuevoEstado;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelProductos;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JButton login;
    private javax.swing.JTextField pass;
    private javax.swing.JLabel pedidos;
    private javax.swing.JLabel precio;
    private javax.swing.JScrollPane scrollTablaHistorial;
    private javax.swing.JScrollPane scrollTablaPedidos;
    private javax.swing.JScrollPane scrollTablaProductos;
    private javax.swing.JPanel sesionCerrada;
    private javax.swing.JPanel sesionIniciada;
    private javax.swing.JTable tablaHistorial;
    private DefaultTableModel historial;
    private javax.swing.JTable tablaPedidos;
    private DefaultTableModel modeloPedidos;
    private javax.swing.JTable tablaProductos;
    private DefaultTableModel medeloProductos;
    private javax.swing.JTextField user;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuarioLogeado;
    private javax.swing.JButton ver;
    private javax.swing.JPanel verPedido;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
